import { UseGuards } from '@nestjs/common';
import { Args, Mutation, Query } from '@nestjs/graphql';

import { MetadataResolver } from 'src/engine/api/graphql/graphql-config/decorators/metadata-resolver.decorator';
import { WorkspaceEntity } from 'src/engine/core-modules/workspace/workspace.entity';
import { AuthWorkspace } from 'src/engine/decorators/auth/auth-workspace.decorator';
import { WorkspaceAuthGuard } from 'src/engine/guards/workspace-auth.guard';

import { AssessRiskInput } from 'src/modules/cpq/dtos/assess-risk.input';
import { CalculatePriceInput } from 'src/modules/cpq/dtos/calculate-price.input';
import { CpqStatusOutput } from 'src/modules/cpq/dtos/cpq-status.output';
import { ConvertQuoteOutput, RenewalJobResultOutput } from 'src/modules/cpq/dtos/renewal-result.output';
import { RiskAssessmentOutput } from 'src/modules/cpq/dtos/risk-assessment.output';
import { PricingResultOutput } from 'src/modules/cpq/dtos/pricing-result.output';
import { SetupResultOutput, TeardownResultOutput } from 'src/modules/cpq/dtos/setup-result.output';

import { CpqContractService } from 'src/modules/cpq/services/cpq-contract.service';
import { CpqPricingService } from 'src/modules/cpq/services/cpq-pricing.service';
import { CpqRenewalService } from 'src/modules/cpq/services/cpq-renewal.service';
import { CpqRiskService } from 'src/modules/cpq/services/cpq-risk.service';
import { CpqSetupService } from 'src/modules/cpq/services/cpq-setup.service';

// GraphQL resolver for CPQ business logic operations.
// Exposes pricing, risk, setup, and quote-to-contract conversion as mutations.
// Standard CRUD is auto-generated by Twenty's metadata layer.
@MetadataResolver()
@UseGuards(WorkspaceAuthGuard)
export class CpqResolver {
  constructor(
    private readonly setupService: CpqSetupService,
    private readonly pricingService: CpqPricingService,
    private readonly contractService: CpqContractService,
    private readonly renewalService: CpqRenewalService,
    private readonly riskService: CpqRiskService,
  ) {}

  // Bootstrap all CPQ custom objects in the workspace
  @Mutation(() => SetupResultOutput)
  async setupCpq(
    @AuthWorkspace() { id: workspaceId }: WorkspaceEntity,
  ): Promise<SetupResultOutput> {
    return this.setupService.setupCpq(workspaceId);
  }

  // Remove all CPQ custom objects from the workspace
  @Mutation(() => TeardownResultOutput)
  async teardownCpq(
    @AuthWorkspace() { id: workspaceId }: WorkspaceEntity,
  ): Promise<TeardownResultOutput> {
    return this.setupService.teardownCpq(workspaceId);
  }

  // Current setup status — which objects exist vs are missing
  @Query(() => CpqStatusOutput)
  async cpqStatus(
    @AuthWorkspace() { id: workspaceId }: WorkspaceEntity,
  ): Promise<CpqStatusOutput> {
    return this.setupService.getSetupStatus(workspaceId);
  }

  // Run the 10-step price waterfall for a line item
  @Mutation(() => PricingResultOutput)
  calculatePrice(
    @Args('input') input: CalculatePriceInput,
  ): PricingResultOutput {
    const result = this.pricingService.calculatePriceWaterfall(input);
    return {
      ...result,
      auditSteps: result.auditSteps as object[],
    };
  }

  // Score a renewal opportunity for risk using 6 weighted signals
  @Mutation(() => RiskAssessmentOutput)
  assessRisk(
    @Args('input') input: AssessRiskInput,
  ): RiskAssessmentOutput {
    const result = this.riskService.assessRenewalRisk({
      ...input,
      dealCloseDate: new Date(input.dealCloseDate),
      contractEndDate: new Date(input.contractEndDate),
    });
    return {
      ...result,
      assessedAt: result.assessedAt.toISOString(),
    };
  }

  // Convert an accepted quote into a contract with subscriptions (atomic)
  @Mutation(() => ConvertQuoteOutput)
  async convertQuoteToContract(
    @AuthWorkspace() { id: workspaceId }: WorkspaceEntity,
    @Args('quoteId') quoteId: string,
  ): Promise<ConvertQuoteOutput> {
    const contractId = await this.contractService.createFromQuote(workspaceId, quoteId);
    return { contractId };
  }

  // Trigger the renewal scan for all expiring contracts in this workspace
  @Mutation(() => RenewalJobResultOutput)
  async runRenewalCheck(
    @AuthWorkspace() { id: workspaceId }: WorkspaceEntity,
  ): Promise<RenewalJobResultOutput> {
    return this.renewalService.runRenewalCheck(workspaceId);
  }
}
