// PhenoTips product catalog — sourced from
// "2024 + 2025 PhenoTips Core & Advanced Pricing Global.xlsx"
// Prices are annual USD unless noted.
// Each entry maps to a PriceConfiguration record in Twenty.

import type { ProductSeedInput } from '@/cpq/hooks/use-cpq-setup';

type CatalogEntry = ProductSeedInput & {
  displayDescription: string;
  isOneTime: boolean;
};

// US / Canada pricing (USD)
export const PHENOTIPS_CATALOG_US: CatalogEntry[] = [
  // ── PT Core Platform ────────────────────────────────────────────────────────
  {
    name: 'PhenoTips Core — Platform Fee',
    productFamily: 'PT Core',
    sku: 'PT-CORE-PLATFORM-US',
    configType: 'flat',
    listPriceAmountMicros: 34_999_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: 'Base annual platform fee — 10 users included',
  },
  {
    name: 'PhenoTips Core — User License 11–50',
    productFamily: 'PT Core',
    sku: 'PT-CORE-USER-11-50-US',
    configType: 'flat',
    listPriceAmountMicros: 899_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: '$899/user/year (users 11–50)',
  },
  {
    name: 'PhenoTips Core — User License 51–99',
    productFamily: 'PT Core',
    sku: 'PT-CORE-USER-51-99-US',
    configType: 'flat',
    listPriceAmountMicros: 799_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: '$799/user/year (users 51–99)',
  },
  {
    name: 'PhenoTips Core — User License 100+',
    productFamily: 'PT Core',
    sku: 'PT-CORE-USER-100PLUS-US',
    configType: 'flat',
    listPriceAmountMicros: 699_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: '$699/user/year (100+ users)',
  },
  {
    name: 'PhenoTips Deployment — Standard',
    productFamily: 'PT Core',
    sku: 'PT-DEPLOY-STD-US',
    configType: 'flat',
    listPriceAmountMicros: 15_000_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: true,
    displayDescription: 'One-time: 4–6 month deployment, basic EHR, PPQ config',
  },
  // ── PPQ ─────────────────────────────────────────────────────────────────────
  {
    name: 'PPQ — Platform Fee',
    productFamily: 'PPQ',
    sku: 'PPQ-PLATFORM-US',
    configType: 'flat',
    listPriceAmountMicros: 9_750_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: 'Annual PPQ platform fee — 10 users included',
  },
  {
    name: 'PPQ — Deployment',
    productFamily: 'PPQ',
    sku: 'PPQ-DEPLOY-US',
    configType: 'flat',
    listPriceAmountMicros: 7_500_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: true,
    displayDescription: 'One-time PPQ deployment fee',
  },
  {
    name: 'PPQ — User License 11–50',
    productFamily: 'PPQ',
    sku: 'PPQ-USER-11-50-US',
    configType: 'flat',
    listPriceAmountMicros: 199_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: '$199/user/year (users 11–50)',
  },
  {
    name: 'PPQ — User License 51–99',
    productFamily: 'PPQ',
    sku: 'PPQ-USER-51-99-US',
    configType: 'flat',
    listPriceAmountMicros: 169_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: '$169/user/year (users 51–99)',
  },
  {
    name: 'PPQ — User License 100+',
    productFamily: 'PPQ',
    sku: 'PPQ-USER-100PLUS-US',
    configType: 'flat',
    listPriceAmountMicros: 129_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: '$129/user/year (100+ users)',
  },
  // ── CRAT ────────────────────────────────────────────────────────────────────
  {
    name: 'CRAT — Platform Fee',
    productFamily: 'CRAT',
    sku: 'CRAT-PLATFORM-US',
    configType: 'flat',
    listPriceAmountMicros: 8_500_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: 'Annual CRAT platform fee — 10 users included',
  },
  {
    name: 'CRAT — User License 11–50',
    productFamily: 'CRAT',
    sku: 'CRAT-USER-11-50-US',
    configType: 'flat',
    listPriceAmountMicros: 199_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: '$199/user/year (users 11–50)',
  },
  {
    name: 'CRAT — User License 100+',
    productFamily: 'CRAT',
    sku: 'CRAT-USER-100PLUS-US',
    configType: 'flat',
    listPriceAmountMicros: 99_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: '$99/user/year (100+ users)',
  },
  // ── Add-Ons ─────────────────────────────────────────────────────────────────
  {
    name: 'Variant Store',
    productFamily: 'Add-Ons',
    sku: 'VARIANT-STORE-US',
    configType: 'flat',
    listPriceAmountMicros: 9_749_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: 'PhenoTips Genomics Suite — annual',
  },
  {
    name: 'NLP Private — Setup',
    productFamily: 'Add-Ons',
    sku: 'NLP-PRIVATE-SETUP-US',
    configType: 'flat',
    listPriceAmountMicros: 9_500_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: true,
    displayDescription: 'One-time NLP Private instance setup',
  },
  {
    name: 'NLP Private — Annual',
    productFamily: 'Add-Ons',
    sku: 'NLP-PRIVATE-ANNUAL-US',
    configType: 'flat',
    listPriceAmountMicros: 4_500_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: 'Annual NLP Private maintenance fee',
  },
  {
    name: 'Managed Authentication / SSO',
    productFamily: 'Add-Ons',
    sku: 'SSO-MANAGED-US',
    configType: 'flat',
    listPriceAmountMicros: 3_499_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: true,
    displayDescription: 'Auth0-based SSO setup with Dev/Ops access',
  },
  {
    name: 'Attachment Storage — 100GB',
    productFamily: 'Add-Ons',
    sku: 'STORAGE-100GB-US',
    configType: 'flat',
    listPriceAmountMicros: 999_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: '$999 per 100GB/year',
  },
  // ── Integrations ────────────────────────────────────────────────────────────
  {
    name: 'FHIR Integration — Setup',
    productFamily: 'Integrations',
    sku: 'FHIR-SETUP-US',
    configType: 'flat',
    listPriceAmountMicros: 9_500_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: true,
    displayDescription: 'One-time FHIR Launcher setup fee',
  },
  {
    name: 'FHIR Integration — Annual',
    productFamily: 'Integrations',
    sku: 'FHIR-ANNUAL-US',
    configType: 'flat',
    listPriceAmountMicros: 3_950_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: 'Annual FHIR recurring maintenance',
  },
  {
    name: 'HL7v2 Interface — Setup',
    productFamily: 'Integrations',
    sku: 'HL7-SETUP-US',
    configType: 'flat',
    listPriceAmountMicros: 14_500_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: true,
    displayDescription: 'One-time HL7v2 interface setup',
  },
  {
    name: 'HL7v2 Interface — Annual',
    productFamily: 'Integrations',
    sku: 'HL7-ANNUAL-US',
    configType: 'flat',
    listPriceAmountMicros: 4_950_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: 'Annual HL7v2 recurring fees',
  },
  {
    name: 'HL7v2 Additional Interface — Setup',
    productFamily: 'Integrations',
    sku: 'HL7-ADDL-SETUP-US',
    configType: 'flat',
    listPriceAmountMicros: 9_500_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: true,
    displayDescription: 'One-time additional HL7v2 interface setup',
  },
  {
    name: 'VPN Fee',
    productFamily: 'Integrations',
    sku: 'VPN-ANNUAL-US',
    configType: 'flat',
    listPriceAmountMicros: 1_500_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: 'Annual VPN fee',
  },
  {
    name: 'OID Fee',
    productFamily: 'Integrations',
    sku: 'OID-FEE-US',
    configType: 'flat',
    listPriceAmountMicros: 850_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: true,
    displayDescription: 'One-time OID registration fee',
  },
  {
    name: 'Custom API — Annual Maintenance',
    productFamily: 'Integrations',
    sku: 'CUSTOM-API-ANNUAL-US',
    configType: 'flat',
    listPriceAmountMicros: 2_950_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: false,
    displayDescription: 'Annual custom API maintenance',
  },
  // ── Consulting ───────────────────────────────────────────────────────────────
  {
    name: 'Professional Services — Hourly',
    productFamily: 'Professional Services',
    sku: 'PS-HOURLY-US',
    configType: 'flat',
    listPriceAmountMicros: 300_000_000,
    listPriceCurrencyCode: 'USD',
    region: 'US',
    currency: 'USD',
    isActive: true,
    isOneTime: true,
    displayDescription: '$300/hour consulting rate',
  },
];

// UK pricing (GBP)
export const PHENOTIPS_CATALOG_UK: CatalogEntry[] = [
  {
    name: 'PhenoTips Core — Platform Fee',
    productFamily: 'PT Core',
    sku: 'PT-CORE-PLATFORM-UK',
    configType: 'flat',
    listPriceAmountMicros: 29_999_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: false,
    displayDescription: '£29,999/year — 10 users included',
  },
  {
    name: 'PhenoTips Core — User License 11–50',
    productFamily: 'PT Core',
    sku: 'PT-CORE-USER-11-50-UK',
    configType: 'flat',
    listPriceAmountMicros: 664_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: false,
    displayDescription: '£664/user/year (users 11–50)',
  },
  {
    name: 'PhenoTips Core — User License 51–99',
    productFamily: 'PT Core',
    sku: 'PT-CORE-USER-51-99-UK',
    configType: 'flat',
    listPriceAmountMicros: 599_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: false,
    displayDescription: '£599/user/year (users 51–99)',
  },
  {
    name: 'PhenoTips Core — User License 100+',
    productFamily: 'PT Core',
    sku: 'PT-CORE-USER-100PLUS-UK',
    configType: 'flat',
    listPriceAmountMicros: 549_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: false,
    displayDescription: '£549/user/year (100+ users)',
  },
  {
    name: 'PhenoTips Deployment — Standard',
    productFamily: 'PT Core',
    sku: 'PT-DEPLOY-STD-UK',
    configType: 'flat',
    listPriceAmountMicros: 12_999_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: true,
    displayDescription: 'One-time standard deployment fee',
  },
  {
    name: 'PPQ — Platform Fee',
    productFamily: 'PPQ',
    sku: 'PPQ-PLATFORM-UK',
    configType: 'flat',
    listPriceAmountMicros: 9_750_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: false,
    displayDescription: '£9,750/year PPQ platform fee',
  },
  {
    name: 'CRAT — Platform Fee',
    productFamily: 'CRAT',
    sku: 'CRAT-PLATFORM-UK',
    configType: 'flat',
    listPriceAmountMicros: 6_500_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: false,
    displayDescription: '£6,500/year CRAT platform fee',
  },
  {
    name: 'NLP Private — Setup',
    productFamily: 'Add-Ons',
    sku: 'NLP-PRIVATE-SETUP-UK',
    configType: 'flat',
    listPriceAmountMicros: 7_500_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: true,
    displayDescription: '£7,500 one-time NLP Private setup',
  },
  {
    name: 'NLP Private — Annual',
    productFamily: 'Add-Ons',
    sku: 'NLP-PRIVATE-ANNUAL-UK',
    configType: 'flat',
    listPriceAmountMicros: 3_500_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: false,
    displayDescription: '£3,500/year NLP Private maintenance',
  },
  {
    name: 'FHIR Integration — Setup',
    productFamily: 'Integrations',
    sku: 'FHIR-SETUP-UK',
    configType: 'flat',
    listPriceAmountMicros: 8_000_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: true,
    displayDescription: '£8,000 one-time FHIR setup',
  },
  {
    name: 'FHIR Integration — Annual',
    productFamily: 'Integrations',
    sku: 'FHIR-ANNUAL-UK',
    configType: 'flat',
    listPriceAmountMicros: 3_200_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: false,
    displayDescription: '£3,200/year FHIR recurring',
  },
  {
    name: 'HL7v2 Interface — Setup',
    productFamily: 'Integrations',
    sku: 'HL7-SETUP-UK',
    configType: 'flat',
    listPriceAmountMicros: 12_000_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: true,
    displayDescription: '£12,000 one-time HL7v2 setup',
  },
  {
    name: 'HL7v2 Interface — Annual',
    productFamily: 'Integrations',
    sku: 'HL7-ANNUAL-UK',
    configType: 'flat',
    listPriceAmountMicros: 3_950_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: false,
    displayDescription: '£3,950/year HL7v2 recurring',
  },
  {
    name: 'Professional Services — Hourly',
    productFamily: 'Professional Services',
    sku: 'PS-HOURLY-UK',
    configType: 'flat',
    listPriceAmountMicros: 250_000_000,
    listPriceCurrencyCode: 'GBP',
    region: 'UK',
    currency: 'GBP',
    isActive: true,
    isOneTime: true,
    displayDescription: '£250/hour consulting rate',
  },
];

// Helper to format currency amounts for display (stored as micros)
export const formatListPrice = (
  amountMicros: number,
  currencyCode: string,
): string => {
  const amount = amountMicros / 1_000_000;
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: currencyCode,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

export type { CatalogEntry };
